# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='say',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('write', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ps', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('git', models.URLField(blank=True)),
                ('head', models.ImageField(upload_to='user')),
            ],
        ),
        migrations.AddField(
            model_name='say',
            name='editor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='say.speaker'),
        ),
        migrations.AddField(
            model_name='say',
            name='say_to',
            field=models.ManyToManyField(blank=True, related_name='reciver', to='say.speaker'),
        ),
    ]
