# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('say', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='ps',
            field=models.CharField(max_length=300),
        ),
    ]
