# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('say', '0002_auto_20180115_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
