# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Classification',
            new_name='classification',
        ),
    ]
