# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171228_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='editorPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='article')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='classification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='article.Classification'),
        ),
    ]
